In [28]:
import os
import json
from collections import Counter

json_dir = "graphes_JSON_Complet"
n_cpu_count = Counter()

for filename in os.listdir(json_dir):
    if filename.endswith(".json"):
        with open(os.path.join(json_dir, filename), "r") as f:
            data = json.load(f)
        
        # Get first node's n_cpu value
        first_node = next(iter(data[list(data.keys())[0]]["node_features"].values()))
        n_cpu = first_node["n_cpus"]
        n_cpu_count[n_cpu] += 1

print("n_cpu values and counts:")
for n_cpu, count in sorted(n_cpu_count.items()):
    print(f"{n_cpu}: {count}")

n_cpu values and counts:
2: 56
3: 55
4: 46
5: 51
6: 52
7: 46
8: 59
9: 56
10: 55
11: 59
12: 48
13: 47
14: 32
15: 53
16: 62
17: 55
18: 56
19: 47
20: 59
21: 38
22: 37
23: 43
24: 47
25: 45
26: 50
27: 53
28: 61
29: 60
30: 38
31: 45
32: 53
33: 52
34: 47
35: 34
36: 45
37: 56
38: 59
39: 43
40: 39
41: 54
42: 41
43: 48
44: 62
45: 43
46: 52
47: 48
48: 40
49: 54
50: 65
51: 45
52: 58
53: 44
54: 53
55: 57
56: 43
57: 42
58: 55
59: 37
60: 44
61: 41
62: 55
63: 58
64: 50
65: 57
66: 60
67: 49
68: 52
69: 51
70: 55
71: 53
72: 56
73: 48
74: 40
75: 53
76: 49
77: 59
78: 49
79: 57
80: 45
81: 35
82: 57
83: 48
84: 45
85: 46
86: 50
87: 54
88: 50
89: 55
90: 59
91: 54
92: 55
93: 56
94: 53
95: 56
96: 57
97: 54
98: 60
99: 46
100: 47


In [29]:
import torch
import torch.nn.functional as F

x = torch.tensor([0.020, -float('inf'), -1.201])
softmax_x = F.softmax(x, dim=-1)
print(softmax_x)


tensor([0.7722, 0.0000, 0.2278])


In [ ]:
import torch
import torch.nn.functional as F

def cost(logits, target):
    probs = F.softmax(logits, dim=-1)
    max_prob= max(probs)
    index=torch.where(probs==max_prob)[0]
    if(index==target):
        return 1
    return 0
    

logits = torch.tensor([[0.020, -float('inf'), -1.201],
                      [0.1, 0, 1.201],
                      [2, 3, 6]])
targets=torch.tensor([1,2,2])

cpt=0
for logit,target in zip(logits,targets):
    cpt+=cost(logit,target)
    
print(cpt/len(targets))

tensor([0.7722, 0.0000, 0.2278])
tensor(0.7722)
max :  tensor([0])  target:  tensor(1)
tensor([0.2036, 0.1842, 0.6122])
tensor(0.6122)
max :  tensor([2])  target:  tensor(2)
tensor([0.0171, 0.0466, 0.9362])
tensor(0.9362)
max :  tensor([2])  target:  tensor(2)
0.6666666666666666


In [49]:
import torch
import torch.nn.functional as F

def compute_accuracy(logits, targets):
    correct = 0
    for logit, target in zip(logits, targets):
        probs = F.softmax(logit, dim=-1)
        pred = torch.argmax(probs).item()
        if pred == target.item():
            correct += 1
    return correct / len(targets)


In [51]:
logits = torch.tensor([[0.020, -float('inf'), -1.201],
                       [0.1, 0, 1.201],
                       [2, 3, 6]])
targets = torch.tensor([0, 0, 0])

accuracy = compute_accuracy(logits, targets)
print("Accuracy:", accuracy)


Accuracy: 0.3333333333333333
